"""change users table

Revision ID: 86a920a29cc0
Revises: e48072a62aa8
Create Date: 2021-12-21 21:21:17.881167

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = '86a920a29cc0'
down_revision = 'e48072a62aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('classified_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'images', 'classifieds', ['classified_id'], ['id'])
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_column('images', 'classified_id')
    # ### end Alembic commands ###
