"""remove user_id from image

Revision ID: ad54cbfd0696
Revises: 88ff0dede1d9
Create Date: 2021-12-26 17:37:01.098860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ad54cbfd0696'
down_revision = '88ff0dede1d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('images_user_id_fkey', 'images', type_='foreignkey')
    op.drop_column('images', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('user_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('images_user_id_fkey', 'images', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
