"""image model changes

Revision ID: e48072a62aa8
Revises: 6ef70aa5a459
Create Date: 2021-12-19 21:47:01.155248

"""
from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision = 'e48072a62aa8'
down_revision = '6ef70aa5a459'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('extension', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'extension')
    # ### end Alembic commands ###
